pipeline:
  name: harness-trigger
  identifier: harnesstrigger
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubOrgLevelConnector
        repoName: harness_pipelines_poc
        build: <+input>
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: trigger
                  identifier: trigger
                  spec:
                    shell: Python
                    command: |-
                      import subprocess
                      import re
                      import sys

                      # Get the latest commit message
                      # commit_message = subprocess.check_output(['git', 'log', '-1', '--pretty=%B']).strip().decode('utf-8')


                      trigger_payload = os.getenv('triggers_payload')
                      pr_number = os.getenv('pr_number')  # Replace with actual environment variable if needed
                      # commit_message = <+trigger.commitMessage>  # Replace with actual env var if needed

                      # print(f"Commit message: {commit_message}")
                      print(f"pr_number: {pr_number}")
                      print(f"trigger_payload: {trigger_payload}")


                      # # Define the regex pattern for the commit message
                      # pattern = r'^(feat|fix|docs|release): [A-Z]+-[0-9]+ .+'

                      # # Check if the commit message matches the pattern
                      # if re.match(pattern, commit_message):
                      #     print("Commit message is valid")
                      #     sys.exit(0)
                      # else:
                      #     print("Invalid commit message. Ensure the message follows the pattern: <type>: <JIRA ID> <message>")
                      #     sys.exit(1)
                    envVariables:
                      pr_number: <+triggers.prNumber>
                      triggers_payload: <+triggers>
