pipeline:
  name: harness-trigger
  identifier: harnesstrigger
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubOrgLevelConnector
        repoName: harness_pipelines_poc
        build: <+input>
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: trigger
                  identifier: trigger
                  spec:
                    shell: Python
                    command: |-
                      import os

                      commit_message = os.getenv('commit_message')
                      pr_number = os.getenv('pr_number')  # Replace with actual environment variable if needed


                      print(f"Commit message: {commit_message}")
                      print(f"pr_number: {pr_number}")
                    envVariables:
                      pr_number: <+trigger.prNumber>
                      commit_message: <+trigger.prTitle>
