pipeline:
  name: harness-trigger
  identifier: harnesstrigger
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubOrgLevelConnector
        repoName: harness_pipelines_poc
        build: <+input>
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: trigger
                  identifier: trigger
                  spec:
                    shell: Python
                    command: |-
                      import subprocess
                      import re
                      import sys

                      # Get the latest commit message
                      commit_message = subprocess.check_output(['git', 'log', '-1', '--pretty=%B']).strip().decode('utf-8')

                      print(f"Commit message: {commit_message}")
                      # Print the PR number and commit message using Harness expression syntax
                      pr_number = os.getenv('TRIGGERS_PRNUMBER', '<+trigger.prNumber>')  # Replace with actual environment variable if needed
                      commit_message = os.getenv('TRIGGERS_COMMITMESSAGE', '<+trigger.commitMessage>')  # Replace with actual env var if needed

                      # Define the regex pattern for the commit message
                      pattern = r'^(feat|fix|docs|release): [A-Z]+-[0-9]+ .+'

                      # Check if the commit message matches the pattern
                      if re.match(pattern, commit_message):
                          print("Commit message is valid")
                          sys.exit(0)
                      else:
                          print("Invalid commit message. Ensure the message follows the pattern: <type>: <JIRA ID> <message>")
                          sys.exit(1)
